---
title: "workout03-michael-xu"
author: "Michael Xu"
date: "4/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# @title
# @var
check_prob <- function(prob) {
  if (prob >= 0 && prob <= 1)  {
    return(TRUE)
  }
  else {
    stop("invalid prob value")
  }
}

# @title
# @var
check_trials <- function(trials) {
  if ( trials > 0){
    return(TRUE)
  }
  else {
    stop("invalid trails")
  }
}

# @title
# @var
check_success <- function(success, trials) {
  for(i in success) {
    if (i < 0 || i > trials) {
      stop("invalid success value")
    }
  }
  return(TRUE)
}

```

#Private Auxiliary Functions
```{r}
aux_mean <- function(trial, prob) {
  return(trial*prob)
}

aux_variance <- function(trial, prob) {
  return (trial * prob * (1 - prob))
}

aux_mode <- function(trial, prob) {
  return(int(trial*prob + prob))
}

aux_skewness <- function(trial, prob) {
  return((1-2*prob)/sqrt(aux_variance(trial,prob)))
}

aux_kurtosis <- function(trial, prob) {
  return((1-6*prob*(1-prob)) / aux_variance(trial,prob))
}
```

#1.3 Function bin_choose()

```{r}
# @title
# @description
# @param
# @return
# @export
# @examples
bin_choose <- function(n,k) {
  if (length(k) > 1) {
    for(i in k) {
      if(i > n) {
        stop("k cannot be greater than n")
      }
    }
  }
  else {
    if (k > n) {
      stop("k cannot be greater than n")
    }
  }
  top <- factorial(n)
  bottom <- factorial(k) * factorial(n-k)
  return(top/bottom)
}

bin_choose(5,2)
bin_choose(5,0)
bin_choose(5,1:3)
```

#1.4 Function bin_probability()
@title
@description
@param
@return
@export
@examples
```{r}
bin_probability <- function(success, trials, prob) {
  check_trials(trials)
  check_prob(prob)
  check_success(success, trials)
  return(prob^success*(1-prob)^(trials-success)*bin_choose(trials, success))
}
bin_probability(2,5,.5)
bin_probability(0:2,5,.5)
bin_probability(55,100,.45)
```


#1.5 Function bin_distribution()
@title
@description
@param
@return
@export
@examples
```{r}
bin_distribution <- function(trials, prob) {
  success <- seq(0,trials,by=1)
  print(success)
  probability <- c()
  for(i in success){
    probability <- c(probability, bin_probability(i,trials,prob))
  }
  
  df <- data.frame("success" = success, "probability" = probability)
  return(df)
}
dis1 <- bin_distribution(trials = 5, prob = .5)

bindis <- function(dis1) {
  plot(dis1)
}
```

#1.6 Function bin_cumulative()
@title
@description
@param
@return
@export
@examples
```{r}
bin_cumulative <- function(trials, prob) {
  df <- bin_distribution(trials, prob)
  cumulative <- c()
  for(i in seq(1,length(df[["probability"]]),by=1)) {
    print(df[["probability"]][[i]])
    if (i != 1) {
      cumulative <- c(cumulative, df[["probability"]][i] + cumulative[i-1])
    } else {
      cumulative <- c(cumulative, df[["probability"]][i])
    }
  }
  # print(cumulative)
  df$cumulative <- cumulative
  return(df)
}

dis2 <- bin_cumulative(5,.5)
dis2
plot(dis2)
```